---
- name: Setup storage driver
  include: setup-storage-driver.yml
  when: >
    storage_driver is defined
    and storage_driver | length > 0

- name: Install on ubuntu
  include: ubuntu/main.yml
  when: ansible_distribution == 'Ubuntu'

- name: Install on Raspbian
  include: debian/main.yml
  when: ansible_distribution == 'Debian'

- name: Setup docker cleanup service
  include: setup-docker-cleanup-service.yml

# We need to start/restart docker immediately because other
# roles will pull/build images during executing the playbook
- name: Enable and restart systemd services
  meta: flush_handlers

- name: Enable/start docker service
  service:
    name: docker
    enabled: true
    state: started
  when: not(
    molecule_docker_environment is defined
    and (molecule_docker_environment | bool)
    )
