---
- include: setup-storage-driver.yml
  when: storage_driver != ''
  register: docker_storage_driver

- include: ubuntu/main.yml
  when: ansible_distribution == 'Ubuntu'

- include: raspbian-jessie.main.yml
  when: ansible_machine == 'armv7l' and ansible_distribution == 'Debian'
    and ansible_distribution_release == 'jessie'

- include: setup-docker-cleanup-service.yml

- include: setup-python-docker.yml
  when: install_pip_docker | bool
