---
- name: Setup storage driver
  include: setup-storage-driver.yml
  when: >
    storage_driver is defined
    and storage_driver | length > 0

- name: Install on ubuntu
  include: ubuntu/main.yml
  when: ansible_distribution == 'Ubuntu'

- name: Install on Raspbian
  include: raspbian-jessie.main.yml
  when: >
    ansible_machine == 'armv7l'
    and ansible_distribution == 'Debian'
    and ansible_distribution_release == 'jessie'

- name: Setup docker cleanup service
  include: setup-docker-cleanup-service.yml

- name: Setup python docker package
  include: setup-python-docker.yml
  when: install_pip_docker | bool

- name: Enable docker service
  service:
    name: docker
    enabled: true

- name: Start docker service
  service:
    name: docker
    state: started
  register: docker_service_start

# We need to start/restart docker immediately because other
# roles will pull/build images during executing the playbook
- name: Flush handlers
  meta: flush_handlers
