---
- include: ubuntu.main.yml
  when: ansible_distribution == 'Ubuntu'

- include: raspbian_jessie.main.yml
  when: ansible_machine == 'armv7l' and ansible_distribution == 'Debian' and ansible_distribution_release == 'jessie'

- include: setup_docker_cleanup_cron_job.yml
  when: docker_cleanup.enabled == true
