---
- name: Setup storage driver
  include: setup-storage-driver.yml
  when: >
    storage_driver is defined
    and storage_driver | length > 0

- name: Install on ubuntu
  include: ubuntu/main.yml
  when: ansible_distribution == 'Ubuntu'

- name: Install on Raspbian
  include: debian/main.yml
  when: ansible_distribution == 'Debian'

- name: Setup docker cleanup service
  include: setup-docker-cleanup-service.yml

- name: Enable docker service
  service:
    name: docker
    enabled: true
  when: not(
    molecule_docker_environment is defined
    and (molecule_docker_environment | bool)
    )

- name: Start docker service
  service:
    name: docker
    state: started
  when: not(
      molecule_docker_environment is defined
      and (molecule_docker_environment | bool)
    )
  register: docker_service_start

# We need to start/restart docker immediately because other
# roles will pull/build images during executing the playbook
- name: Flush handlers
  meta: flush_handlers
