---
- name: Add repository key from keyserver
  apt_key:
    keyserver: hkp://pgp.mit.edu:80
    id: 58118E89F3A912897C070ADBF76221572C52609D

- name: Add dockerproject.org repository
  apt_repository:
    repo: 'deb https://apt.dockerproject.org/repo ubuntu-trusty main'
    update_cache: yes
    state: present

- name: Install docker-engine package
  apt:
    name: docker-engine
    state: latest
    update_cache: yes
    cache_valid_time: 600
