---
- name: Setup storage driver
  include_tasks: setup-storage-driver.yml
  when: >
    docker_storage_driver is defined
    and docker_storage_driver | length > 0

- name: Install needed dependencies for devicemapper
  apt:
    name:
      - thin-provisioning-tools
    state: present
    update_cache: false
  when: docker_storage_driver == 'devicemapper'

- name: Install docker apt package
  include_tasks: install-apt-package.yml
  when: ansible_distribution == 'Ubuntu'
    or ansible_distribution == 'Debian'

- name: Setup docker cleanup service
  include_tasks: setup-docker-cleanup-service.yml

# We need to start/restart docker immediately because other
# roles will pull/build images during executing the playbook
- name: Enable and restart systemd services
  meta: flush_handlers

- name: Enable/start docker service
  service:
    name: docker
    enabled: true
    state: started
  when: not(
    molecule_docker_environment is defined
    and (molecule_docker_environment | bool)
    )
