---
- include: ubuntu-trusty.main.yml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'trusty'

- include: ubuntu-xenial.main.yml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'xenial'
