---
- name: Create cleanup service
  copy:
    src: ./files/docker-cleanup.service
    dest: "/etc/systemd/system/docker-cleanup.service"
    owner: root
    group: root
    mode: 0644
  notify: Reload docker-cleanup service

- name: Create cleanup timer
  template:
    src: docker-cleanup.timer.j2
    dest: "/etc/systemd/system/docker-cleanup.timer"
    owner: root
    group: root
    mode: 0644
  notify: Reload docker-cleanup timer
