---
- name: Create cleanup service
  copy:
    src: ./files/docker-cleanup.service
    dest: "/etc/systemd/system/docker-cleanup.service"
    owner: root
    group: root
    mode: 0644
  register: cleanup_service
  notify: Reload systemd

- name: Create cleanup timer
  template:
    src: docker-cleanup.timer.j2
    dest: "/etc/systemd/system/docker-cleanup.timer"
    owner: root
    group: root
    mode: 0644
  notify: Reload systemd

- name: Enable cleanup service
  service:
    name: docker-cleanup.service
    enabled: true
  # in docker environment this task would fail
  when: cleanup_enabled is defined
    and cleanup_enabled | bool
    and not (
      molecule_docker_environment is defined
      and molecule_docker_environment | bool
    )

- name: Enable cleanup timer
  service:
    name: docker-cleanup.timer
    enabled: true
  when: cleanup_enabled is defined
    and cleanup_enabled | bool
    and not (
      molecule_docker_environment is defined
      and molecule_docker_environment | bool
    )

- name: Start cleanup timer
  service:
    name: docker-cleanup.timer
    state: started
  when: (
      cleanup_enabled is defined
      and cleanup_enabled | bool
    )
    and not (
      molecule_docker_environment is defined
      and molecule_docker_environment | bool
    )

- name: Stop cleanup timer
  service:
    name: docker-cleanup.timer
    enabled: false
    state: stopped
  when: cleanup_enabled is not defined
    or not (cleanup_enabled | bool)
    and not (
      molecule_docker_environment is defined
      and molecule_docker_environment | bool
    )
