---
- include_vars:
    file: ubuntu.yml

- name: Install needed dependencies
  apt:
    name:
      - wget
      - apt-transport-https
    state: latest
    update_cache: yes

- name: Add repository key from keyserver
  apt_key:
    url: "{{repo.key_url}}"
    state: present

- name: Add repository
  template:
    src: apt.source.list.j2
    dest: /etc/apt/sources.list.d/download_docker_com_linux_ubuntu.list
  register: apt_repo

- name: Update apt chache
  apt:
    update_cache: yes
  when: apt_repo.changed

- name: Install docker-engine package
  apt:
    name: docker-ce
    state: latest

- include: setup-storage-driver.yml
  when: storage_driver != ''
  register: docker_storage_driver

- name: Restart docker service
  service: name=docker state=restarted
  when: docker_storage_driver.changed
