---
- name: Install docker engine package
  apt:
    name:
      - docker.io
    state: latest
    update_cache: yes

- name: Install needed dependencies for devicemapper
  apt:
    name:
      - thin-provisioning-tools
    state: latest
    update_cache: no
  when: storage_driver == 'devicemapper'

- include: setup-storage-driver.yml
  when: storage_driver != ''
  register: docker_storage_driver

- name: Enable docker service
  service:
    name: docker
    enabled: yes

- name: Restart docker service
  service:
    name: docker
    state: restarted
  when: docker_storage_driver.changed

- name: Start docker service (if not started already)
  service:
    name: docker
    state: started
