disk = './.vagrant/tmp/secondDisk.vdi'

Vagrant.configure("2") do |config|
#   config.vm.box = "ubuntu/xenial64"
  config.vm.box = "ubuntu/bionic64"
#   config.vm.box = "ubuntu/focal64"

  config.vm.network "private_network", ip: "192.168.33.68"

  config.vm.provider "virtualbox" do |v|
    v.name = "ansible_docker"

    # create the second disk and attach it
    unless File.exist?(disk)
      v.customize ['createhd', '--filename', disk, '--variant', 'Standard', '--size', 10 * 1024]
    end

    v.customize ['storageattach', :id,  '--storagectl', 'SCSI', '--port', 2, '--device', 0, '--type', 'hdd', '--medium', disk]
  end

  config.vm.provision "shell", inline: <<-SHELL
    if ! mount | grep -q /dev/mapper/my_vol_group-my_volume ; then
      # https://www.unix.com/shell-programming-and-scripting/207169-non-interactive-fdisk-partition-script.html
      echo "n
      p
      1


      t
      8e
      w" | fdisk /dev/sdc

      pvcreate /dev/sdc1
      vgcreate my_vol_group /dev/sdc1
      lvcreate -L 1G -n my_volume my_vol_group

      # device available at:
      ls -la /dev/my_vol_group/my_volume

      mkfs.xfs -n ftype=1 /dev/my_vol_group/my_volume

      mkdir -p /var/lib/docker

      echo "\n/dev/mapper/my_vol_group-my_volume   /var/lib/docker        xfs   defaults        0 0\n" >> /etc/fstab

      mount /var/lib/docker
    fi
  SHELL
end
