---
- name: Reload systemd
  systemd:
    daemon_reload: true
  # in docker environment this handler would fail
  when: not (
      molecule_docker_environment is defined
      and molecule_docker_environment | bool
    )

- name: Restart docker
  service:
    name: docker
    state: restarted
  when: not (
    docker_service_start is defined
    and docker_service_start.changed
    )
