---
dependency:
  name: galaxy

driver:
  name: vagrant

platforms:
  - name: ansible-docker-noble
    box: cloud-image/ubuntu-24.04
  - name: ansible-docker-jammy
    box: cloud-image/ubuntu-22.04
  - name: ansible-docker-focal
    box: cloud-image/ubuntu-20.04
  - name: ansible-docker-bookworm
    box: cloud-image/debian-12
    groups:
      - debian
  - name: ansible-docker-bullseye
    box: cloud-image/debian-11
    groups:
      - debian

provisioner:
  name: ansible
  playbooks:
    converge: ../shared/converge.yml
  inventory:
    group_vars:
      debian:
        ansible_python_interpreter: /usr/bin/python3

verifier:
  name: ansible
