---
dependency:
  name: galaxy

driver:
  name: vagrant
  provider:
    name: virtualbox

platforms:
  - name: ansible-docker-jammy
    box: generic/ubuntu2204
  - name: ansible-docker-focal
    box: generic/ubuntu2004
  - name: ansible-docker-bookworm
    box: generic/debian12
    groups:
      - debian
  - name: ansible-docker-bullseye
    box: generic/debian11
    groups:
      - debian

provisioner:
  name: ansible
  playbooks:
    converge: ../shared/converge.yml
  inventory:
    group_vars:
      debian:
        ansible_python_interpreter: /usr/bin/python3

verifier:
  name: ansible
