---
- name: Verify
  hosts: all
  become: true

  tasks:
    - name: should provide docker executable
      command: docker --version
      register: docker_version
      changed_when: false

    - name: should start cleanup timer
      service:
        name: docker-cleanup.timer
        state: started
      register: cleanup_timer
      failed_when: cleanup_timer.changed

    - name: should pull nginx docker image
      command: docker pull nginx:1.17.9-alpine
      changed_when: false
