---
dependency:
  name: galaxy

lint: |
  set -e
  yamllint . --strict
  ansible-lint

driver:
  name: docker

platforms:
  - name: docker-jammy
    image: docker.io/borisskert/python3:jammy
    pull: true
    pre_build_image: true
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    groups:
      - docker
  - name: docker-focal
    image: docker.io/borisskert/python3:focal
    pull: true
    pre_build_image: true
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    groups:
      - docker

  - name: docker-bookworm
    image: docker.io/borisskert/python3:bookworm
    pull: true
    pre_build_image: true
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    groups:
      - docker
      - debian

  - name: docker-bullseye
    image: docker.io/borisskert/python3:bullseye
    pull: true
    pre_build_image: true
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    groups:
      - docker
      - debian

provisioner:
  name: ansible
  playbooks:
    converge: ../shared/converge.yml
  inventory:
    group_vars:
      docker:
        molecule_docker_environment: true
      debian:
        ansible_python_interpreter: /usr/bin/python3
    host_vars:
      docker-jammy:
        test_image_to_pull: nginx:1.17.9-alpine
        test_port: 8080
        test_container_name: nginx-for-jammy
      docker-focal:
        test_image_to_pull: nginx:1.17.8-alpine
        test_port: 8081
        test_container_name: nginx-for-focal
      docker-bookworm:
        test_image_to_pull: nginx:1.17.6-alpine
        test_port: 8083
        test_container_name: nginx-for-bookworm
      docker-bullseye:
        test_image_to_pull: nginx:1.17.5-alpine
        test_port: 8084
        test_container_name: nginx-for-bullseye

verifier:
  name: ansible
