---
- name: Verify
  hosts: all
  become: true

  tasks:
    - name: should provide docker executable
      command: docker --version
      register: docker_version
      changed_when: false

    - name: should pull nginx docker image
      command: "docker pull {{ test_image_to_pull }}"
      changed_when: false
