---
- name: Install needed dependencies for devicemapper
  apt:
    name:
      - thin-provisioning-tools
    state: present
    update_cache: false
  when: storage_driver == 'devicemapper'

- name: Install docker-ce package for Ubuntu
  include: install-docker-ce.main.yml
  when: ansible_distribution_release != 'focal'

# We have to install 'docker.io' package in
# Ubuntu 20.04 Focal Fossa unless Docker builds
# an official release package
- name: Install docker io for Ubuntu 20.04 (focal)
  include: install-docker-io.yml
  when: ansible_distribution_release == 'focal'

- name: Enable docker service
  service:
    name: docker
    enabled: true

- name: Start docker service (if not started already)
  service:
    name: docker
    state: started
