---
- name: Install needed dependencies for devicemapper
  apt:
    name:
      - thin-provisioning-tools
    state: latest
    update_cache: no
  when: storage_driver == 'devicemapper'

- include: install-docker-ce.main.yml
  when: ansible_distribution_release != 'focal'

# We have to install 'docker.io' package in Ubuntu 20.04 Focal Fossa unless Docker builds an official release package
- include: install-docker-io.yml
  when: ansible_distribution_release == 'focal'

- name: Enable docker service
  service:
    name: docker
    enabled: yes

- name: Restart docker service
  service:
    name: docker
    state: restarted
  when: docker_storage_driver.changed

- name: Start docker service (if not started already)
  service:
    name: docker
    state: started
