---
- name: Install needed dependencies for devicemapper
  apt:
    name:
      - thin-provisioning-tools
    state: present
    update_cache: false
  when: docker_storage_driver == 'devicemapper'

- name: Install docker-ce package for Ubuntu
  include: install-docker-ce.main.yml

- name: Setup python docker package
  include: setup-python-docker.yml
  when: docker_install_pip_package | bool
