---
- name: Converge
  hosts: all
  become: true

  roles:
    - role: ansible-docker
      docker_storage_driver: overlay2
      docker_cleanup_enabled: true
      docker_cleanup_on_calendar: daily
      docker_install_pip_package: true
