---
- name: Converge
  hosts: all
  become: true

  roles:
    - role: ansible-docker
      storage_driver: overlay2
      cleanup_enabled: true
      cleanup_on_calendar: daily
      install_pip_docker: true
