---
- name: Converge
  hosts: all
  become: true

  tasks:
    - name: Testing role
      ansible.builtin.include_role:
        name: "ansible-docker"
      vars:
        docker_storage_driver: overlay2
        docker_cleanup_enabled: true
        docker_cleanup_on_calendar: daily
